// GENERATED by scripts/gen_questions.py — do not edit by hand.
// Source of truth: second-brain/Projects/lovli-io-vectors/*.csv

export type Question = {
  code: string; section: string; text: string; weight: number;
  type: "slider" | "choice" | "multi" | "text";
  low?: string; high?: string; options?: string[]; maxLen?: number;
  showIf?: { code: string; in?: number[]; answered?: boolean };
};

export type Step = { id: string; title: string; intro?: string; special?: boolean; items: string[] };

export const QUESTIONS: Record<string, Question> = {
  "VB_01": {
    "code": "VB_01",
    "section": "VIBE",
    "text": "Skąd czerpiesz energię do życia?",
    "weight": 3,
    "type": "slider",
    "low": "Energia płynie do mnie od ludzi — towarzystwo mnie ładuje",
    "high": "Energia płynie do mnie ze spokoju i czasu samemu"
  },
  "VB_02": {
    "code": "VB_02",
    "section": "VIBE",
    "text": "Jak wolisz spędzać czas?",
    "weight": 3,
    "type": "slider",
    "low": "Wolę głośne i żywe miejsca — dużo ludzi i ruchu",
    "high": "Wolę ciszę i spokojne otoczenie"
  },
  "VB_03": {
    "code": "VB_03",
    "section": "VIBE",
    "text": "Jak podejmujesz ważne decyzje?",
    "weight": 4,
    "type": "slider",
    "low": "Słucham serca — emocje i intuicja są moim kompasem",
    "high": "Analizuję i liczę — logika jest moim kompasem"
  },
  "VB_04": {
    "code": "VB_04",
    "section": "VIBE",
    "text": "Jak wyrażasz emocje?",
    "weight": 3,
    "type": "slider",
    "low": "Wyrażam to co czuję — otwarcie i spontanicznie",
    "high": "Jestem powściągliwy/a — emocje przeżywam bardziej wewnętrznie"
  },
  "VB_05": {
    "code": "VB_05",
    "section": "VIBE",
    "text": "Jak działasz kiedy coś trzeba zrobić?",
    "weight": 3,
    "type": "slider",
    "low": "Reaguję szybko — działam na instynkt i pierwszą myśl",
    "high": "Zatrzymuję się i przemyślam zanim zrobię krok"
  },
  "VB_06": {
    "code": "VB_06",
    "section": "VIBE",
    "text": "Jak planujesz swoje życie i czas?",
    "weight": 4,
    "type": "slider",
    "low": "Lubię spontaniczność — najlepsze rzeczy dzieją się bez planu",
    "high": "Lubię planować — struktura i przygotowanie dają mi spokój"
  },
  "VB_07": {
    "code": "VB_07",
    "section": "VIBE",
    "text": "Co bardziej cię napędza w życiu?",
    "weight": 4,
    "type": "slider",
    "low": "Zmiana i nowe wyzwania — stagnacja mnie zabija",
    "high": "Stabilność i pewność — wiem na czym stoję"
  },
  "VB_08": {
    "code": "VB_08",
    "section": "VIBE",
    "text": "Jak reagujesz na nieporządek i chaos?",
    "weight": 3,
    "type": "slider",
    "low": "Chaos mi nie przeszkadza — adaptuję się i płynę z prądem",
    "high": "Potrzebuję porządku — bałagan obniża moją efektywność"
  },
  "VB_09": {
    "code": "VB_09",
    "section": "VIBE",
    "text": "Czego szukasz w bliskiej relacji?",
    "weight": 4,
    "type": "slider",
    "low": "Głębokiej intymności i emocjonalnej bliskości",
    "high": "Przestrzeni i wzajemnego szacunku dla niezależności"
  },
  "VB_10": {
    "code": "VB_10",
    "section": "VIBE",
    "text": "Jak budujesz zaufanie do nowych osób?",
    "weight": 3,
    "type": "slider",
    "low": "Otwieram się szybko — ufam ludziom dopóki nie zawiedą",
    "high": "Potrzebuję czasu — zaufanie buduję stopniowo i ostrożnie"
  },
  "VB_11": {
    "code": "VB_11",
    "section": "VIBE",
    "text": "Jak wyglądają twoje idealne wakacje?",
    "weight": 2,
    "type": "slider",
    "low": "Dużo aktywności — zwiedzanie ludzie przygody non stop",
    "high": "Spokój i regeneracja — delektuję się wolnym tempem"
  },
  "VB_12": {
    "code": "VB_12",
    "section": "VIBE",
    "text": "Co jest dla ciebie ważniejsze w związku?",
    "weight": 4,
    "type": "slider",
    "low": "Wolność i własna przestrzeń — nawet w związku muszę być sobą",
    "high": "Zaangażowanie i wspólne życie — razem to znaczy razem"
  },
  "VAL_01a": {
    "code": "VAL_01a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważna jest dla ciebie uczciwość i prawdomówność?",
    "weight": 5,
    "type": "slider",
    "low": "Nie jest dla mnie szczególnie ważna",
    "high": "Jest absolutnie kluczowa — nie wyobrażam sobie bez niej"
  },
  "VAL_01b": {
    "code": "VAL_01b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Na ile uczciwy/a i prawdomówny/a jesteś w codziennym życiu?",
    "weight": 5,
    "type": "slider",
    "low": "Często odpuszczam — życie wymaga kompromisów",
    "high": "Konsekwentnie staram się być uczciwy/a we wszystkim"
  },
  "VAL_02a": {
    "code": "VAL_02a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważne jest dla ciebie życie zgodne z własnym sumieniem i zasadami?",
    "weight": 4,
    "type": "slider",
    "low": "Działam pragmatycznie — zasady to drogowskaz nie nakaz",
    "high": "Zasady moralne są fundamentem moich decyzji"
  },
  "VAL_02b": {
    "code": "VAL_02b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Jak często rezygnujesz z czegoś co chciałeś/aś zrobić bo byłoby to niezgodne z twoimi zasadami?",
    "weight": 4,
    "type": "slider",
    "low": "Rzadko — staram się być pragmatyczny/a",
    "high": "Regularnie — moje zasady są granicą której nie przekraczam"
  },
  "VAL_03a": {
    "code": "VAL_03a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważna jest dla ciebie odpowiedzialność za swoje czyny i słowa?",
    "weight": 5,
    "type": "slider",
    "low": "Staram się ale nie robię z tego kultu",
    "high": "Jest dla mnie bardzo ważna — biorę odpowiedzialność za siebie i swoje wybory"
  },
  "VAL_03b": {
    "code": "VAL_03b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Kiedy coś idzie nie tak — jak reagujesz?",
    "weight": 5,
    "type": "slider",
    "low": "Szukam okoliczności i kontekstu który to tłumaczy",
    "high": "Przede wszystkim pytam siebie co mogłem/am zrobić inaczej"
  },
  "VAL_04a": {
    "code": "VAL_04a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważna jest dla ciebie głęboka refleksja i dążenie do mądrości?",
    "weight": 4,
    "type": "slider",
    "low": "Wolę działać niż rozkminiać",
    "high": "Refleksja i głębsze rozumienie rzeczy są dla mnie ważne"
  },
  "VAL_04b": {
    "code": "VAL_04b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Jak często zatrzymujesz się by przemyśleć swoje życie i wybory?",
    "weight": 4,
    "type": "slider",
    "low": "Rzadko — żyję raczej spontanicznie",
    "high": "Regularnie — refleksja jest częścią mojej rutyny"
  },
  "VAL_05a": {
    "code": "VAL_05a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważna jest dla ciebie sprawiedliwość — w relacjach i w świecie?",
    "weight": 3,
    "type": "slider",
    "low": "Staram się być fair ale nie angażuję się aktywnie",
    "high": "Sprawiedliwość to dla mnie wartość o którą warto walczyć"
  },
  "VAL_05b": {
    "code": "VAL_05b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Jak często reagujesz gdy widzisz niesprawiedliwość wobec innych?",
    "weight": 3,
    "type": "slider",
    "low": "Najczęściej milczę — to nie moja sprawa",
    "high": "Zazwyczaj reaguję — nie lubię przechodzić obok"
  },
  "VAL_06a": {
    "code": "VAL_06a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważne jest dla ciebie ciągłe doskonalenie się w tym co robisz?",
    "weight": 4,
    "type": "slider",
    "low": "Robię co do mnie należy — nie gonię za perfekcją",
    "high": "Ciągły rozwój i dążenie do mistrzostwa są dla mnie kluczowe"
  },
  "VAL_06b": {
    "code": "VAL_06b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Ile czasu i energii aktywnie wkładasz w rozwijanie swoich umiejętności?",
    "weight": 4,
    "type": "slider",
    "low": "Uczę się gdy muszę albo gdy nadarzy się okazja",
    "high": "Systematycznie inwestuję w swój rozwój — to mój priorytet"
  },
  "VAL_07a": {
    "code": "VAL_07a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważne jest dla ciebie poznawanie nowych idei wiedzy i perspektyw?",
    "weight": 3,
    "type": "slider",
    "low": "Cenię sprawdzone rozwiązania bardziej niż nowości",
    "high": "Ciekawość i ciągłe uczenie się to część mnie"
  },
  "VAL_07b": {
    "code": "VAL_07b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Jak często aktywnie szukasz nowych informacji lub perspektyw różniących się od twoich?",
    "weight": 3,
    "type": "slider",
    "low": "Rzadko — trzymam się tego co znam",
    "high": "Regularnie — lubię być zaskoczony/a i zmieniać zdanie"
  },
  "VAL_08a": {
    "code": "VAL_08a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważna jest dla ciebie wytrwałość — trzymanie się raz obranego celu?",
    "weight": 4,
    "type": "slider",
    "low": "Umiem odpuścić gdy sytuacja tego wymaga",
    "high": "Wytrwałość i konsekwencja to coś czego się trzymam"
  },
  "VAL_08b": {
    "code": "VAL_08b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Jak zazwyczaj reagujesz gdy napotykasz poważną przeszkodę w dążeniu do celu?",
    "weight": 4,
    "type": "slider",
    "low": "Dość szybko zmieniam kierunek lub odpuszczam",
    "high": "Szukam innej drogi — rezygnacja jest ostatecznością"
  },
  "VAL_09a": {
    "code": "VAL_09a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważne jest dla ciebie życie w zgodzie z tym kim naprawdę jesteś?",
    "weight": 5,
    "type": "slider",
    "low": "Adaptuję się do oczekiwań — to część życia społecznego",
    "high": "Autentyczność jest dla mnie fundamentem — nie gram ról"
  },
  "VAL_09b": {
    "code": "VAL_09b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Jak często zachowujesz się inaczej niż czujesz bo obawiasz się reakcji innych?",
    "weight": 5,
    "type": "slider",
    "low": "Dość często — zależy mi na tym co myślą inni",
    "high": "Rzadko — wolę być sobą nawet jeśli ktoś tego nie lubi"
  },
  "VAL_10a": {
    "code": "VAL_10a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważna jest dla ciebie odwaga — podejmowanie ryzyka i wychodzenie poza strefę komfortu?",
    "weight": 3,
    "type": "slider",
    "low": "Cenię bezpieczeństwo — ryzyko biorę tylko gdy muszę",
    "high": "Odwaga i przekraczanie własnych granic są dla mnie ważne"
  },
  "VAL_10b": {
    "code": "VAL_10b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Jak często świadomie robisz coś co cię przeraża lub jest trudne?",
    "weight": 3,
    "type": "slider",
    "low": "Unikam takich sytuacji gdy to możliwe",
    "high": "Regularnie — dyskomfort traktuję jako sygnał że rosnę"
  },
  "VAL_11a": {
    "code": "VAL_11a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważna jest dla ciebie empatia — rozumienie i współodczuwanie z innymi?",
    "weight": 5,
    "type": "slider",
    "low": "Jestem raczej pragmatyczny/a — skupiam się na rozwiązaniach",
    "high": "Empatia i troska o innych są dla mnie bardzo ważne"
  },
  "VAL_11b": {
    "code": "VAL_11b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Jak reagujesz gdy ktoś bliski przeżywa trudny czas?",
    "weight": 5,
    "type": "slider",
    "low": "Oferuję praktyczną pomoc — rozwiązania są ważniejsze niż słowa",
    "high": "Najpierw jestem przy nich emocjonalnie — słucham i staram się rozumieć"
  },
  "VAL_12a": {
    "code": "VAL_12a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważna jest dla ciebie lojalność i wierność w relacjach?",
    "weight": 5,
    "type": "slider",
    "low": "Lojalność jest ważna ale okoliczności mają znaczenie",
    "high": "Lojalność i wierność to wartości które traktuję absolutnie"
  },
  "VAL_12b": {
    "code": "VAL_12b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Czy zdarzyło ci się złamać daną obietnicę lub zaufanie kogoś bliskiego?",
    "weight": 5,
    "type": "slider",
    "low": "Zdarzyło się — życie jest skomplikowane",
    "high": "Staram się nigdy — to dla mnie przekroczona granica"
  },
  "VAL_13a": {
    "code": "VAL_13a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważne jest dla ciebie budowanie głębokiego zaufania w relacji?",
    "weight": 5,
    "type": "slider",
    "low": "Zaufanie buduje się samo — nie trzeba o nim myśleć",
    "high": "Zaufanie jest fundamentem każdej bliskiej relacji dla mnie"
  },
  "VAL_13b": {
    "code": "VAL_13b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Jak otwarty/a jesteś na to by pokazać komuś swoje słabości i lęki?",
    "weight": 5,
    "type": "slider",
    "low": "Trudno mi się otwierać — chronię swoje wnętrze",
    "high": "Otwieram się gdy czuję bezpieczeństwo — wrażliwość nie jest słabością"
  },
  "VAL_14a": {
    "code": "VAL_14a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważny jest dla ciebie szacunek do drugiej osoby — niezależnie od różnic?",
    "weight": 4,
    "type": "slider",
    "low": "Szacunek zależy od tego jak ktoś się zachowuje",
    "high": "Szacunek to fundament — każdy go zasługuje jako punkt wyjścia"
  },
  "VAL_14b": {
    "code": "VAL_14b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Jak zachowujesz się wobec osób które mają zupełnie inne poglądy niż ty?",
    "weight": 4,
    "type": "slider",
    "low": "Trudno mi — dystans albo dyskusja to moja naturalna reakcja",
    "high": "Szanuję ich prawo do własnych poglądów nawet gdy się nie zgadzam"
  },
  "VAL_15a": {
    "code": "VAL_15a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważna jest dla ciebie współpraca i zdolność do działania razem?",
    "weight": 3,
    "type": "slider",
    "low": "Wolę działać samodzielnie — efektywność jest ważniejsza",
    "high": "Wspólne działanie i budowanie razem są dla mnie ważne"
  },
  "VAL_15b": {
    "code": "VAL_15b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Jak zazwyczaj zachowujesz się gdy pracujesz z innymi nad wspólnym projektem?",
    "weight": 3,
    "type": "slider",
    "low": "Wolę przejąć inicjatywę i zadania do samodzielnej realizacji",
    "high": "Aktywnie buduję synergię — razem dajemy lepszy wynik"
  },
  "VAL_16a": {
    "code": "VAL_16a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważna jest dla ciebie wdzięczność — docenianie tego co masz i kto jest w twoim życiu?",
    "weight": 3,
    "type": "slider",
    "low": "Żyję teraźniejszością — rzadko zatrzymuję się na docenienie",
    "high": "Wdzięczność jest ważną częścią tego jak patrzę na życie"
  },
  "VAL_16b": {
    "code": "VAL_16b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Jak często aktywnie wyrażasz wdzięczność wobec osób ważnych w twoim życiu?",
    "weight": 3,
    "type": "slider",
    "low": "Rzadko — zakładam że wiedzą",
    "high": "Regularnie — chcę żeby czuli się docenieni"
  },
  "VAL_17a": {
    "code": "VAL_17a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważna jest dla ciebie niezależność i możliwość samodzielnego decydowania o swoim życiu?",
    "weight": 4,
    "type": "slider",
    "low": "Cenię bliskość i wspólne decyzje bardziej niż autonomię",
    "high": "Niezależność i suwerenność w decyzjach są dla mnie kluczowe"
  },
  "VAL_17b": {
    "code": "VAL_17b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Jak reagujesz gdy ktoś bliski próbuje wpłynąć na twoje decyzje lub styl życia?",
    "weight": 4,
    "type": "slider",
    "low": "Jestem otwarty/a — inni często widzą więcej niż ja",
    "high": "Bronię swojej autonomii — sam/a decyduję o swoim życiu"
  },
  "VAL_18a": {
    "code": "VAL_18a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważna jest dla ciebie skuteczność — rzeczywiste osiąganie zamierzonych celów?",
    "weight": 3,
    "type": "slider",
    "low": "Ważniejszy jest kierunek i wartości niż konkretne wyniki",
    "high": "Wyniki i skuteczność są dla mnie ważnym miernikiem"
  },
  "VAL_18b": {
    "code": "VAL_18b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Jak regularnie realizujesz plany i zobowiązania które sobie stawiasz?",
    "weight": 3,
    "type": "slider",
    "low": "Często odkładam lub zmieniam kierunek",
    "high": "Zazwyczaj kończę to co zaczynam — zobowiązania traktuję poważnie"
  },
  "VAL_19a": {
    "code": "VAL_19a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważne jest dla ciebie aktywne kształtowanie swojej rzeczywistości zamiast reagowania na nią?",
    "weight": 3,
    "type": "slider",
    "low": "Adaptuję się do tego co przynosi życie",
    "high": "Wolę działać i kreować niż czekać i reagować"
  },
  "VAL_19b": {
    "code": "VAL_19b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Jak często sam/a inicjujesz zmiany w swoim życiu zamiast czekać aż coś cię do nich zmusi?",
    "weight": 3,
    "type": "slider",
    "low": "Zazwyczaj zmieniam gdy muszę",
    "high": "Regularnie — aktywnie przebudowuję swoje życie i nawyki"
  },
  "VAL_20a": {
    "code": "VAL_20a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważna jest dla ciebie zaradność — radzenie sobie w trudnych i nieprzewidywalnych sytuacjach?",
    "weight": 3,
    "type": "slider",
    "low": "Wolę mieć system wsparcia i pomoc innych",
    "high": "Zaradność i samodzielność w kryzysie są ważną częścią mnie"
  },
  "VAL_20b": {
    "code": "VAL_20b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Jak zazwyczaj reagujesz gdy znajdziesz się w trudnej i nieznanej sytuacji bez gotowego rozwiązania?",
    "weight": 3,
    "type": "slider",
    "low": "Szukam pomocy i wsparcia od innych",
    "high": "Włączam tryb rozwiązywania — analizuję i działam samodzielnie"
  },
  "VAL_21a": {
    "code": "VAL_21a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważne jest dla ciebie życie z intencją — świadome dążenie do konkretnych celów?",
    "weight": 4,
    "type": "slider",
    "low": "Płynę z życiem — cele tworzą się same",
    "high": "Mam konkretne cele i staram się świadomie do nich dążyć"
  },
  "VAL_21b": {
    "code": "VAL_21b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Jak często wracasz do swoich celów i sprawdzasz czy twoje działania z nimi się zgadzają?",
    "weight": 4,
    "type": "slider",
    "low": "Rzadko — działam intuicyjnie",
    "high": "Regularnie — moje decyzje są zakorzenione w celach"
  },
  "VAL_22a": {
    "code": "VAL_22a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważne jest dla ciebie dbanie o zdrowie fizyczne?",
    "weight": 4,
    "type": "slider",
    "low": "Zdrowie jest ważne ale nie robię z tego priorytetu",
    "high": "Dbanie o ciało jest fundamentem mojego funkcjonowania"
  },
  "VAL_22b": {
    "code": "VAL_22b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Jak regularnie dbasz o aktywność fizyczną i zdrowy styl życia?",
    "weight": 4,
    "type": "slider",
    "low": "Nieregularnie — staram się jak mogę",
    "high": "Mam stałe nawyki zdrowotne i trzymam się ich"
  },
  "VAL_23a": {
    "code": "VAL_23a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważny jest dla ciebie wewnętrzny spokój i harmonia emocjonalna?",
    "weight": 3,
    "type": "slider",
    "low": "Wolę intensywność i pasję niż spokój",
    "high": "Spokój wewnętrzny i równowaga są dla mnie ważne"
  },
  "VAL_23b": {
    "code": "VAL_23b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Jak dobrze radzisz sobie z utrzymaniem spokoju w stresujących sytuacjach?",
    "weight": 3,
    "type": "slider",
    "low": "Stres łatwo mnie przytłacza",
    "high": "Zazwyczaj zachowuję spokój nawet pod presją"
  },
  "VAL_24a": {
    "code": "VAL_24a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważna jest dla ciebie dyscyplina i regularność w codziennym życiu?",
    "weight": 3,
    "type": "slider",
    "low": "Wolę elastyczność i dostosowywanie się na bieżąco",
    "high": "Dyscyplina i stałe nawyki są podstawą mojego życia"
  },
  "VAL_24b": {
    "code": "VAL_24b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Jak regularnie trzymasz się swoich nawyków i rutyn nawet gdy masz mniej motywacji?",
    "weight": 3,
    "type": "slider",
    "low": "Odpuszczam gdy nie mam siły lub ochoty",
    "high": "Trzymam się nawyków nawet gdy nie mam na to ochoty"
  },
  "VAL_25a": {
    "code": "VAL_25a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważna jest dla ciebie uważność — świadome i pełne przeżywanie chwili obecnej?",
    "weight": 3,
    "type": "slider",
    "low": "Żyję raczej przyszłością i planami",
    "high": "Obecność i uważność są dla mnie ważnymi wartościami"
  },
  "VAL_25b": {
    "code": "VAL_25b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Jak często udaje ci się być naprawdę obecnym/ą — bez myśli o przeszłości lub przyszłości?",
    "weight": 3,
    "type": "slider",
    "low": "Rzadko — moje myśli uciekają",
    "high": "Regularnie — praca nad obecnością jest częścią mojego życia"
  },
  "VAL_26a": {
    "code": "VAL_26a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważna jest dla ciebie stabilność i przewidywalność w życiu?",
    "weight": 4,
    "type": "slider",
    "low": "Lubię zmiany i nowe rozdania — przewidywalność mnie nudzi",
    "high": "Stabilność i bezpieczeństwo są dla mnie bardzo ważne"
  },
  "VAL_26b": {
    "code": "VAL_26b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Jak budujesz stabilność w swoim życiu — zawodowym i osobistym?",
    "weight": 4,
    "type": "slider",
    "low": "Żyję bardziej z dnia na dzień niż długoterminowo",
    "high": "Aktywnie buduję stabilne fundamenty w każdej sferze"
  },
  "VAL_27a": {
    "code": "VAL_27a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważna jest dla ciebie kreatywność i tworzenie nowych rzeczy?",
    "weight": 3,
    "type": "slider",
    "low": "Wolę optymalizować i ulepszać istniejące rozwiązania",
    "high": "Tworzenie i innowacja są ważną częścią tego jak działam"
  },
  "VAL_27b": {
    "code": "VAL_27b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Jak często aktywnie tworzysz coś nowego — w pracy w domu lub dla siebie?",
    "weight": 3,
    "type": "slider",
    "low": "Rzadko — raczej realizuję to co jest ustalone",
    "high": "Regularnie — tworzenie jest naturalną częścią mojego życia"
  },
  "VAL_28a": {
    "code": "VAL_28a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważna jest dla ciebie jakość tego co robisz?",
    "weight": 3,
    "type": "slider",
    "low": "Ważniejsze jest ukończenie i efektywność niż perfekcja",
    "high": "Zależy mi na wysokim standardzie wszystkiego co robię"
  },
  "VAL_28b": {
    "code": "VAL_28b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Jak często inwestujesz dodatkowy czas i wysiłek żeby zrobić coś naprawdę dobrze?",
    "weight": 3,
    "type": "slider",
    "low": "Rzadko — skończone jest lepsze niż idealne",
    "high": "Regularnie — nie lubię oddawać czegoś poniżej swojego standardu"
  },
  "VAL_29a": {
    "code": "VAL_29a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważne jest dla ciebie pomaganie innym i działanie na rzecz dobra wspólnego?",
    "weight": 3,
    "type": "slider",
    "low": "Skupiam się najpierw na sobie i najbliższych",
    "high": "Służba i działanie dla innych są ważną częścią mojego życia"
  },
  "VAL_29b": {
    "code": "VAL_29b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Jak często aktywnie angażujesz się w pomaganie innym — poza swoim najbliższym kręgiem?",
    "weight": 3,
    "type": "slider",
    "low": "Rzadko — nie mam na to zasobów lub czasu",
    "high": "Regularnie — wolontariat pomoc wsparcie są częścią mojego życia"
  },
  "VAL_30a": {
    "code": "VAL_30a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważna jest dla ciebie odpowiedzialność za wspólnotę — lokalną narodową lub globalną?",
    "weight": 3,
    "type": "slider",
    "low": "Żyję raczej prywatnie — sprawy publiczne mnie nie angażują",
    "high": "Angażuję się w sprawy wspólnoty — czuję za nią odpowiedzialność"
  },
  "VAL_30b": {
    "code": "VAL_30b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Jak często aktywnie działasz na rzecz swojej społeczności lub spraw które uważasz za ważne?",
    "weight": 3,
    "type": "slider",
    "low": "Rzadko — intencje są ale nie przekładam ich na działanie",
    "high": "Regularnie — moje zaangażowanie jest widoczne i konkretne"
  },
  "VAL_31a": {
    "code": "VAL_31a",
    "section": "WARTOŚCI - Ważność",
    "text": "Jak ważne jest dla ciebie przekazywanie wiedzy i wspieranie rozwoju innych?",
    "weight": 2,
    "type": "slider",
    "low": "Skupiam się na własnym rozwoju bardziej niż na uczeniu innych",
    "high": "Wspieranie i mentoring innych jest częścią tego kim jestem"
  },
  "VAL_31b": {
    "code": "VAL_31b",
    "section": "WARTOŚCI - Realizacja",
    "text": "Jak często aktywnie pomagasz komuś się rozwijać lub coś lepiej zrozumieć?",
    "weight": 2,
    "type": "slider",
    "low": "Rzadko — nie szukam takiej roli",
    "high": "Regularnie — uczenie i dzielenie się wiedzą sprawia mi satysfakcję"
  },
  "VAL_32a": {
    "code": "VAL_32a",
    "section": "FUNDAMENTALNE",
    "text": "Jakie jest twoje podejście do wiary i religii?",
    "weight": 3,
    "type": "choice",
    "options": [
      "Katolik/czka praktykujący/a",
      "Katolik/czka niepraktykujący/a",
      "Inny chrześcijanin/ka — praktykujący/a",
      "Inny chrześcijanin/ka — niepraktykujący/a",
      "Prawosławny/a",
      "Islam",
      "Judaizm",
      "Inna religia",
      "Duchowość bez religii",
      "Agnostyk/czka",
      "Ateista/tka",
      "Wolę nie odpowiadać"
    ]
  },
  "VAL_32b": {
    "code": "VAL_32b",
    "section": "FUNDAMENTALNE",
    "text": "Jak ważna jest wiara w twoim codziennym życiu i w wyborach które podejmujesz?",
    "weight": 5,
    "type": "slider",
    "low": "Wiara nie ma wpływu na moje codzienne decyzje",
    "high": "Wiara jest centrum mojego życia i decyzji",
    "showIf": {
      "code": "VAL_32a",
      "answered": true
    }
  },
  "FUND_05a": {
    "code": "FUND_05a",
    "section": "FUNDAMENTALNE",
    "text": "Jaki model partnerstwa jest ci najbliższy?",
    "weight": 5,
    "type": "slider",
    "low": "Tradycyjny podział ról — on zarabia ona buduje dom i wychowuje dzieci",
    "high": "Partnerstwo 50/50 — każdy daje tyle samo we wszystkich sferach"
  },
  "FUND_05b": {
    "code": "FUND_05b",
    "section": "FUNDAMENTALNE",
    "text": "Jak ważne jest dla ciebie żeby twój partner/partnerka miał/a podobne podejście do podziału ról?",
    "weight": 4,
    "type": "slider",
    "low": "Jestem elastyczny/a — możemy to wypracować razem",
    "high": "To musi być spójne od początku — różnica tu tworzy napięcia"
  },
  "FUND_06a": {
    "code": "FUND_06a",
    "section": "FUNDAMENTALNE",
    "text": "Czym jest dla ciebie praca?",
    "weight": 4,
    "type": "slider",
    "low": "Praca to narzędzie — środek do życia i realizacji innych celów",
    "high": "Praca to powołanie — źródło sensu i tożsamości"
  },
  "FUND_07a": {
    "code": "FUND_07a",
    "section": "FUNDAMENTALNE",
    "text": "Jak podchodzisz do pieniędzy i finansów?",
    "weight": 4,
    "type": "slider",
    "low": "Wydaję i cieszę się chwilą — pieniądze są po to by ich używać",
    "high": "Oszczędzam i buduję bezpieczeństwo — fundament daje wolność"
  },
  "GOAL_01a": {
    "code": "GOAL_01a",
    "section": "CELE ŻYCIOWE",
    "text": "Jak ważne jest dla ciebie osiągnięcie mistrzostwa w tym co robisz zawodowo lub artystycznie?",
    "weight": 4,
    "type": "slider",
    "low": "Robię co lubię bez presji bycia mistrzem",
    "high": "Dążenie do najwyższego poziomu w tym co robię jest ważnym celem"
  },
  "GOAL_02a": {
    "code": "GOAL_02a",
    "section": "CELE ŻYCIOWE",
    "text": "Jak ważne jest dla ciebie tworzenie trwałych dzieł lub osiągnięć które przetrwają?",
    "weight": 3,
    "type": "slider",
    "low": "Ważniejsze jest doświadczenie procesu niż zostawienie śladu",
    "high": "Chcę zostawić po sobie trwały wkład — dzieło projekt dziedzictwo"
  },
  "GOAL_03a": {
    "code": "GOAL_03a",
    "section": "CELE ŻYCIOWE",
    "text": "Jak ważny jest dla ciebie aktywny rozwój intelektualny przez całe życie?",
    "weight": 3,
    "type": "slider",
    "low": "Uczę się gdy potrzebuję — nie gonię za wiedzą dla samej wiedzy",
    "high": "Ciągłe uczenie się i poszerzanie horyzontów to ważny cel"
  },
  "GOAL_04a": {
    "code": "GOAL_04a",
    "section": "CELE ŻYCIOWE",
    "text": "Jak ważny jest dla ciebie rozwój duchowy i pogłębianie relacji z transcendencją lub własną głębią?",
    "weight": 4,
    "type": "slider",
    "low": "Duchowość nie jest moim priorytetem",
    "high": "Rozwój duchowy jest ważnym celem i kierunkiem mojego życia"
  },
  "GOAL_06a": {
    "code": "GOAL_06a",
    "section": "CELE ŻYCIOWE",
    "text": "Jak ważne jest dla ciebie zbudowanie głębokiej trwałej relacji romantycznej?",
    "weight": 5,
    "type": "slider",
    "low": "To jeden z wielu celów — nie nadrzędny",
    "high": "Trwała miłość i bliska relacja to jeden z najważniejszych celów mojego życia"
  },
  "VAL_33a": {
    "code": "VAL_33a",
    "section": "FUNDAMENTALNE",
    "text": "Czy chcesz mieć dzieci?",
    "weight": 3,
    "type": "choice",
    "options": [
      "Tak — bardzo tego chcę",
      "Tak — raczej tak",
      "Jeszcze nie wiem",
      "Raczej nie",
      "Nie — zdecydowanie nie",
      "Mam już dzieci i chcę więcej",
      "Mam już dzieci i nie chcę więcej"
    ]
  },
  "VAL_33b": {
    "code": "VAL_33b",
    "section": "FUNDAMENTALNE",
    "text": "Jak ważne jest to dla ciebie w kontekście partnera/partnerki — czy wasza odpowiedź musi być spójna?",
    "weight": 5,
    "type": "slider",
    "low": "Jestem elastyczny/a — moglibyśmy to razem przemyśleć",
    "high": "To jest warunek dla mnie — musimy być zgodni zanim cokolwiek zaczniemy",
    "showIf": {
      "code": "VAL_33a",
      "answered": true
    }
  },
  "GOAL_07a": {
    "code": "GOAL_07a",
    "section": "CELE ŻYCIOWE",
    "text": "Jak ważne jest dla ciebie aktywne rodzicielstwo i wychowanie dzieci jako życiowy cel?",
    "weight": 5,
    "type": "slider",
    "low": "Dzieci to ważna sfera ale nie definiuje mojego życia",
    "high": "Bycie dobrym rodzicem i wychowanie dzieci to jeden z moich głównych celów",
    "showIf": {
      "code": "VAL_33a",
      "in": [
        0,
        1,
        5
      ]
    }
  },
  "GOAL_08a": {
    "code": "GOAL_08a",
    "section": "CELE ŻYCIOWE",
    "text": "Jak ważne jest dla ciebie budowanie głębokich i trwałych przyjaźni?",
    "weight": 3,
    "type": "slider",
    "low": "Przyjaźnie tworzą się same — nie inwestuję w nie aktywnie",
    "high": "Wartościowe przyjaźnie to ważna część mojego życia"
  },
  "GOAL_09a": {
    "code": "GOAL_09a",
    "section": "CELE ŻYCIOWE",
    "text": "Jak ważna jest dla ciebie przynależność do wspólnoty — religijnej etnicznej lokalnej lub innej?",
    "weight": 3,
    "type": "slider",
    "low": "Jestem raczej indywidualistą/ką",
    "high": "Przynależność do wspólnoty jest ważną częścią mojej tożsamości"
  },
  "GOAL_10a": {
    "code": "GOAL_10a",
    "section": "CELE ŻYCIOWE",
    "text": "Jak ważna jest dla ciebie niezależność finansowa i wolność ekonomiczna?",
    "weight": 4,
    "type": "slider",
    "low": "Stabilny dochód wystarczy — nie gonię za bogactwem",
    "high": "Wolność finansowa i niezależność ekonomiczna są ważnym celem"
  },
  "GOAL_13a": {
    "code": "GOAL_13a",
    "section": "CELE ŻYCIOWE",
    "text": "Jak ważne jest dla ciebie bycie częścią czegoś większego niż ty sam/a — idei misji sprawy?",
    "weight": 4,
    "type": "slider",
    "low": "Skupiam się na własnym życiu i bliskich",
    "high": "Bycie częścią większej misji jest ważnym motorem mojego życia"
  },
  "GOAL_14a": {
    "code": "GOAL_14a",
    "section": "CELE ŻYCIOWE",
    "text": "Jak ważne jest dla ciebie działanie etyczne i moralne jako świadomy cel?",
    "weight": 4,
    "type": "slider",
    "low": "Staram się być uczciwy/a — ale nie czynię z tego misji",
    "high": "Życie zgodne z etyką jest świadomym i ważnym celem mojego życia"
  },
  "GOAL_19a": {
    "code": "GOAL_19a",
    "section": "CELE ŻYCIOWE",
    "text": "Jak ważne jest dla ciebie budowanie czegoś trwałego — firmy systemu organizacji rodziny?",
    "weight": 4,
    "type": "slider",
    "low": "Wolę być dobry/a w tym co robię niż tworzyć coś trwałego",
    "high": "Budowanie czegoś trwałego co przetrwa jest ważnym celem"
  },
  "GOAL_22a": {
    "code": "GOAL_22a",
    "section": "CELE ŻYCIOWE",
    "text": "Jak ważne jest dla ciebie aktywne poznawanie świata i różnych kultur?",
    "weight": 2,
    "type": "slider",
    "low": "Cenię znane środowisko — podróże nie są priorytetem",
    "high": "Poznawanie świata i różnorodności jest ważną częścią mojego życia"
  },
  "PAS_SET": {
    "code": "PAS_SET",
    "section": "PASJE",
    "text": "Wybierz swoje pasje i zainteresowania (możesz wybrać tyle ile chcesz)",
    "weight": 3,
    "type": "multi",
    "options": [
      "🎨 Sztuka i rysowanie",
      "📸 Fotografia",
      "🎵 Muzyka (słuchanie)",
      "🎸 Muzyka (tworzenie/granie)",
      "🍳 Gotowanie i kulinaria",
      "🏃 Sporty wytrzymałościowe",
      "💪 Sporty siłowe",
      "🥋 Sporty walki",
      "⚽ Sporty zespołowe",
      "🪂 Sporty ekstremalne i przygoda",
      "🧘 Joga i medytacja",
      "🏔️ Trekking i góry",
      "✈️ Podróże i eksploracja",
      "🌿 Natura i ekologia",
      "📚 Czytanie i literatura",
      "🧠 Filozofia i psychologia",
      "🌱 Samorozwój i coaching",
      "🚀 Nauka i technologia",
      "💻 Programowanie",
      "🎮 Gry video",
      "🎲 Gry planszowe i RPG",
      "🎬 Film i kino",
      "🎭 Teatr i sztuki performatywne",
      "🙏 Duchowość i religia",
      "🤝 Wolontariat i działalność społeczna",
      "🚗 Motoryzacja",
      "👗 Moda i styl",
      "🌻 Ogrodnictwo i uprawa",
      "🥗 Zdrowe odżywianie"
    ]
  },
  "PAS_TEXT": {
    "code": "PAS_TEXT",
    "section": "PASJE",
    "text": "Opiszesz swoją pasję której nie ma na liście?",
    "weight": 1,
    "type": "text",
    "maxLen": 500
  },
  "LS_01a": {
    "code": "LS_01a",
    "section": "LIFESTYLE",
    "text": "Jak spędzasz idealny wolny wieczór?",
    "weight": 2,
    "type": "slider",
    "low": "Wychodzę — spotkania imprezy nowe twarze i energia tłumu",
    "high": "Zostaję w domu — dobra książka film rozmowa w małym gronie"
  },
  "LS_02a": {
    "code": "LS_02a",
    "section": "LIFESTYLE",
    "text": "Gdzie wolisz mieszkać i żyć?",
    "weight": 2,
    "type": "slider",
    "low": "Miasto — szybkie tempo kultura restauracje życie nocne i możliwości",
    "high": "Natura i spokój — wieś przedmieścia cichy rytm życia"
  },
  "LS_03a": {
    "code": "LS_03a",
    "section": "LIFESTYLE",
    "text": "Jak reagujesz na różnorodność kulturową i nowe perspektywy?",
    "weight": 2,
    "type": "slider",
    "low": "Cenię swoje korzenie i znane wartości — nowe nie zawsze znaczy lepsze",
    "high": "Fascynuje mnie różnorodność — inne kultury i perspektywy mnie wzbogacają"
  },
  "LS_04a": {
    "code": "LS_04a",
    "section": "LIFESTYLE",
    "text": "Jak ważne jest dla ciebie zdrowe odżywianie i świadomy styl życia?",
    "weight": 2,
    "type": "slider",
    "low": "Jem to co lubię — bez specjalnych restrykcji ani zasad",
    "high": "Dbam o to co jem i jak żyję — to ważna część mojego stylu"
  },
  "OPQ_01": {
    "code": "OPQ_01",
    "section": "PYTANIA OTWARTE",
    "text": "Co cię ukształtowało? Opisz jedno trudne doświadczenie które zbudowało cię jako człowieka.",
    "weight": 3,
    "type": "text",
    "maxLen": 500
  },
  "OPQ_02": {
    "code": "OPQ_02",
    "section": "PYTANIA OTWARTE",
    "text": "Opisz trzy momenty w swoim życiu w których czułeś/aś się naprawdę szczęśliwy/a — co było w nich wspólnego?",
    "weight": 3,
    "type": "text",
    "maxLen": 500
  },
  "OPQ_03": {
    "code": "OPQ_03",
    "section": "PYTANIA OTWARTE",
    "text": "Czego szukasz na tej platformie?",
    "weight": 3,
    "type": "choice",
    "options": [
      "Związku długotrwałego",
      "Relacji z potencjałem na związek",
      "Przyjaźni i wartościowej znajomości",
      "Jeszcze nie wiem — sprawdzam"
    ]
  }
};

export const STEPS: Step[] = [
  {
    "id": "vibe-1",
    "title": "Twój vibe · 1/3",
    "items": [
      "VB_01",
      "VB_02",
      "VB_03",
      "VB_04"
    ],
    "intro": "Zanim przejdziemy do wartości — chcemy zrozumieć, jak jesteś zbudowany/a. Nie ma dobrych ani złych odpowiedzi."
  },
  {
    "id": "vibe-2",
    "title": "Twój vibe · 2/3",
    "items": [
      "VB_05",
      "VB_06",
      "VB_07",
      "VB_08"
    ]
  },
  {
    "id": "vibe-3",
    "title": "Twój vibe · 3/3",
    "items": [
      "VB_09",
      "VB_10",
      "VB_11",
      "VB_12"
    ]
  },
  {
    "id": "values-1",
    "title": "Twoje wartości · 1/10",
    "items": [
      "VAL_01a",
      "VAL_01b",
      "VAL_02a",
      "VAL_02b",
      "VAL_03a",
      "VAL_03b"
    ],
    "intro": "Każdą wartość oceniasz na dwóch poziomach: jak bardzo jest dla ciebie ważna i jak bardzo realizujesz ją w życiu. Ta różnica jest kluczowa."
  },
  {
    "id": "values-2",
    "title": "Twoje wartości · 2/10",
    "items": [
      "VAL_04a",
      "VAL_04b",
      "VAL_05a",
      "VAL_05b",
      "VAL_06a",
      "VAL_06b"
    ]
  },
  {
    "id": "values-3",
    "title": "Twoje wartości · 3/10",
    "items": [
      "VAL_07a",
      "VAL_07b",
      "VAL_08a",
      "VAL_08b",
      "VAL_09a",
      "VAL_09b"
    ]
  },
  {
    "id": "values-4",
    "title": "Twoje wartości · 4/10",
    "items": [
      "VAL_10a",
      "VAL_10b",
      "VAL_11a",
      "VAL_11b",
      "VAL_12a",
      "VAL_12b"
    ]
  },
  {
    "id": "values-5",
    "title": "Twoje wartości · 5/10",
    "items": [
      "VAL_13a",
      "VAL_13b",
      "VAL_14a",
      "VAL_14b",
      "VAL_15a",
      "VAL_15b"
    ]
  },
  {
    "id": "values-6",
    "title": "Twoje wartości · 6/10",
    "items": [
      "VAL_16a",
      "VAL_16b",
      "VAL_17a",
      "VAL_17b",
      "VAL_18a",
      "VAL_18b"
    ]
  },
  {
    "id": "values-7",
    "title": "Twoje wartości · 7/10",
    "items": [
      "VAL_19a",
      "VAL_19b",
      "VAL_20a",
      "VAL_20b",
      "VAL_21a",
      "VAL_21b"
    ]
  },
  {
    "id": "values-8",
    "title": "Twoje wartości · 8/10",
    "items": [
      "VAL_22a",
      "VAL_22b",
      "VAL_23a",
      "VAL_23b",
      "VAL_24a",
      "VAL_24b"
    ]
  },
  {
    "id": "values-9",
    "title": "Twoje wartości · 9/10",
    "items": [
      "VAL_25a",
      "VAL_25b",
      "VAL_26a",
      "VAL_26b",
      "VAL_27a",
      "VAL_27b"
    ]
  },
  {
    "id": "values-10",
    "title": "Twoje wartości · 10/10",
    "items": [
      "VAL_28a",
      "VAL_28b",
      "VAL_29a",
      "VAL_29b",
      "VAL_30a",
      "VAL_30b",
      "VAL_31a",
      "VAL_31b"
    ]
  },
  {
    "id": "faith",
    "title": "Pytanie o sens",
    "items": [
      "VAL_32a",
      "VAL_32b"
    ],
    "intro": "To jedno z ważniejszych pytań. Odpowiedź wpłynie znacząco na to, z kim zostaniesz dopasowany/a.",
    "special": true
  },
  {
    "id": "fund",
    "title": "Twoje priorytety życiowe",
    "items": [
      "FUND_05a",
      "FUND_05b",
      "FUND_06a",
      "FUND_07a"
    ],
    "intro": "Teraz pytania o to, jak widzisz swoją przyszłość."
  },
  {
    "id": "goals-1",
    "title": "Twoje cele życiowe · 1/3",
    "items": [
      "GOAL_01a",
      "GOAL_02a",
      "GOAL_03a",
      "GOAL_04a"
    ],
    "intro": "Co jest dla ciebie naprawdę ważne na końcu drogi?"
  },
  {
    "id": "goals-2",
    "title": "Twoje cele życiowe · 2/3",
    "items": [
      "GOAL_06a"
    ]
  },
  {
    "id": "children",
    "title": "Pytanie o przyszłość",
    "items": [
      "VAL_33a",
      "VAL_33b"
    ],
    "intro": "Jedno z pytań o najwyższej wadze. Odpowiedź decyduje o fundamentalnej kompatybilności.",
    "special": true
  },
  {
    "id": "goals-3",
    "title": "Twoje cele życiowe · 3/3",
    "items": [
      "GOAL_07a",
      "GOAL_08a",
      "GOAL_09a",
      "GOAL_10a"
    ]
  },
  {
    "id": "goals-4",
    "title": "Sens i trwałość",
    "items": [
      "GOAL_13a",
      "GOAL_14a",
      "GOAL_19a",
      "GOAL_22a"
    ]
  },
  {
    "id": "passions",
    "title": "Twoje pasje",
    "items": [
      "PAS_SET",
      "PAS_TEXT"
    ],
    "intro": "Pasje to bonus, nie kryterium — pomagają w rozmowie."
  },
  {
    "id": "lifestyle",
    "title": "Twój styl życia",
    "items": [
      "LS_01a",
      "LS_02a",
      "LS_03a",
      "LS_04a"
    ]
  },
  {
    "id": "open",
    "title": "Twoja historia",
    "items": [
      "OPQ_01",
      "OPQ_02",
      "OPQ_03"
    ],
    "intro": "Ostatnie pytania są najważniejsze. Weź chwilę. Liczy się autentyczność — te odpowiedzi nigdy nie trafiają do silnika dopasowań."
  }
];

export const PASSION_OPTIONS = ["🎨 Sztuka i rysowanie", "📸 Fotografia", "🎵 Muzyka (słuchanie)", "🎸 Muzyka (tworzenie/granie)", "🍳 Gotowanie i kulinaria", "🏃 Sporty wytrzymałościowe", "💪 Sporty siłowe", "🥋 Sporty walki", "⚽ Sporty zespołowe", "🪂 Sporty ekstremalne i przygoda", "🧘 Joga i medytacja", "🏔️ Trekking i góry", "✈️ Podróże i eksploracja", "🌿 Natura i ekologia", "📚 Czytanie i literatura", "🧠 Filozofia i psychologia", "🌱 Samorozwój i coaching", "🚀 Nauka i technologia", "💻 Programowanie", "🎮 Gry video", "🎲 Gry planszowe i RPG", "🎬 Film i kino", "🎭 Teatr i sztuki performatywne", "🙏 Duchowość i religia", "🤝 Wolontariat i działalność społeczna", "🚗 Motoryzacja", "👗 Moda i styl", "🌻 Ogrodnictwo i uprawa", "🥗 Zdrowe odżywianie"];
